# -*- coding: utf-8 -*-
"""PRODIGY_GA_05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PczxOa0wp-t1cKYL8X4b4AqtT9VybZGW
"""

!pip install tensorflow tensorflow_hub pillow gradio

import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
import gradio as gr

from PIL import Image

model = hub.load(
    "https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2"
)

def load_image(image):

    image = Image.open(image)

    image = image.resize((512,512))

    image = np.array(image)

    image = image.astype(np.float32)

    image = image / 255.0

    image = image[np.newaxis,:]

    return tf.constant(image)

def style_transfer(
    content_path,
    style_path
):

    content_image = load_image(
        content_path
    )

    style_image = load_image(
        style_path
    )

    stylized_image = model(
        content_image,
        style_image
    )[0]

    result = stylized_image[0].numpy()

    return result

with gr.Blocks(theme=gr.themes.Soft()) as demo:

    gr.Markdown("""
    # 🎨 Neural Style Transfer

    ### Content Image + Style Image → Stylized Image

    Upload a content image and a style image.
    The model will transfer the artistic style to the content image.
    """)

    with gr.Row():

        content_input = gr.Image(
            type="filepath",
            label="📷 Content Image"
        )

        style_input = gr.Image(
            type="filepath",
            label="🎨 Style Image"
        )

        output_image = gr.Image(
            label="✨ Stylized Image"
        )

    generate_btn = gr.Button(
        "🚀 Apply Style"
    )

    generate_btn.click(
        fn=style_transfer,
        inputs=[
            content_input,
            style_input
        ],
        outputs=output_image
    )

demo.launch(share=True)

